[terminal.shell]
program = "C:\\Windows\\System32\\wsl.exe"
args = ["~"]

[window.padding]
x = 2
y = 2

[font]
size = 12
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

[colors.primary]
background = "#11111b"
foreground = "#cdd6f4"
dim_foreground = "#9399b2"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#11111b"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#11111b"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#11111b"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#11111b"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#cdd6f4"
background = "#313244"

[colors.hints.start]
foreground = "#11111b"
background = "#f9e2af"

[colors.hints.end]
foreground = "#cdd6f4"
background = "#313244"

[colors.selection]
text = "#cdd6f4"
background = "#45475a"

[colors.normal]
black = "#313244"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#6c7086"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"
