-- Generated by scripts/render-theme. Edit themes/current.toml instead.
return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = false,
    priority = 1000,
    opts = {
      flavour = "mocha",
      term_colors = true,
      custom_highlights = function(colors)
        return {
          Normal = { bg = colors.crust },
          NormalNC = { bg = colors.crust },
          SignColumn = { bg = colors.crust },
          StatusLine = { bg = colors.mantle },
          WinSeparator = { fg = colors.overlay0 },
          CursorLine = { bg = colors.mantle },
          ColorColumn = { bg = colors.mantle },
          Visual = { bg = colors.surface1 },
          NormalFloat = { bg = colors.mantle },
          FloatBorder = { fg = colors.mauve, bg = colors.mantle },
          Pmenu = { bg = colors.mantle },
          PmenuSel = { bg = colors.surface1, fg = colors.text },
        }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin-mocha",
    },
  },
}
